In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
# creating a new dataset
from sklearn.datasets import make_classification

In [4]:
# also make_classification function se data standarized form mai ata hy so we dont have to repeat that step
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

# no of features = 10, means no of independent features (columns)
# no of classes, means how many categoreis, here we chose 2
#  X = independent feature
# Y = output feature

In [5]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [6]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=15)


In [8]:
# model training
from sklearn.linear_model import LogisticRegression
# when penalty l1 l2 applied makes this logistic model into lasso or ridge regression accordingly, as logistic is type of linear model coz we finding a best fit line to divide datapooints into classes

# ridge is used for overfitting and lasso is used for feature selection 
# c is inversely propotional to lambda which is a imp factor in ridge and lasso regression
# class weight is used to balance imbalance dataset, we can decide weight of classes accordinlgy if theyre imbalanced


logistic = LogisticRegression()

In [9]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [10]:
y_pred = logistic.predict(X_test)

In [11]:
# tells about our new data that what proabability it has to fall in diff classes, whichever class has more probability that means new point will fall on that category or give that output
# here we had two classes so its giving probability of each test point according to both classes


logistic.predict_proba(X_test)

array([[9.89982061e-01, 1.00179394e-02],
       [9.81564732e-01, 1.84352676e-02],
       [1.74722738e-03, 9.98252773e-01],
       [9.48052078e-01, 5.19479217e-02],
       [6.79745877e-01, 3.20254123e-01],
       [8.57637307e-01, 1.42362693e-01],
       [9.83706289e-01, 1.62937109e-02],
       [9.90902788e-01, 9.09721193e-03],
       [8.75802329e-01, 1.24197671e-01],
       [8.65452066e-01, 1.34547934e-01],
       [9.83544149e-01, 1.64558514e-02],
       [1.48175976e-01, 8.51824024e-01],
       [4.66110623e-01, 5.33889377e-01],
       [9.08202083e-03, 9.90917979e-01],
       [1.34569854e-01, 8.65430146e-01],
       [7.97765698e-01, 2.02234302e-01],
       [9.50394674e-01, 4.96053262e-02],
       [9.87121968e-01, 1.28780318e-02],
       [3.78895329e-01, 6.21104671e-01],
       [1.35492989e-01, 8.64507011e-01],
       [3.31601568e-01, 6.68398432e-01],
       [9.38937899e-01, 6.10621013e-02],
       [8.46108695e-02, 9.15389130e-01],
       [8.86959048e-01, 1.13040952e-01],
       [5.496784

In [12]:
# thru classification report we get precison , recall and all
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score = accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)

0.8333333333333334
[[128  30]
 [ 20 122]]


In [13]:
score = accuracy_score(y_test,y_pred)
print(score)


0.8333333333333334


In [14]:
print(score)


0.8333333333333334


In [15]:
# since it is a binary classification we will get 2 x 2 confusion matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[128  30]
 [ 20 122]]


In [16]:
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.86      0.81      0.84       158
           1       0.80      0.86      0.83       142

    accuracy                           0.83       300
   macro avg       0.83      0.83      0.83       300
weighted avg       0.84      0.83      0.83       300



# hyperparameter tuning and cross validation


In [17]:
# checking which is the best paramter for out model, thats why taking all possible parameters in list
model = LogisticRegression()
penalty = ['l1','l2','elasticnet']

In [18]:
c_values = [100,10,0.1,0.01]

In [19]:
solver = ['newton-cg','lbfgs','liblinear','sag','saga']


In [20]:
# these are all possible  values for parameters of logistic reg model, we want to see which value is best for our model
# then we will assign that value permanently to our model's paramter respectively for each parameter
params = dict(penalty=penalty,C=c_values,solver=solver)

In [21]:
# gridsearchcv
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()
# n = 5, shuffle = false, by default

In [22]:
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)
# njobs = -1 so that it uses all processors in our system

In [23]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [24]:
grid.fit(X_train,y_train)

/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/user/Desktop/a/venv/lib/python3.10/sit

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [25]:
# the best parameters have been selected for our model, after trying all the combinations of given option, these are the best paramters
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [26]:
grid.best_score_

np.float64(0.8742857142857143)

In [27]:
y_pred = grid.predict(X_test)

In [28]:
# thru classification report we get precison , recall and all
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score = accuracy_score(y_test,y_pred)
print("score: ",score)
cm = confusion_matrix(y_test,y_pred)
print("confusion matrix: ",cm)
print(classification_report(y_test,y_pred))

score:  0.85
confusion matrix:  [[130  28]
 [ 17 125]]
              precision    recall  f1-score   support

           0       0.88      0.82      0.85       158
           1       0.82      0.88      0.85       142

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



# Randomizes Search cv

grid search takes all the combinations of all the paramters provided, it will make time so in order to overcome this we use randomized search cv , which takes random combination and then finds out which combination suits best on our problem statement

The main difference is that in large no of dataset randomized search cv will take less time than grid search cv

In [29]:
from sklearn.model_selection import RandomizedSearchCV

In [30]:
model = LogisticRegression()
randomcv = RandomizedSearchCV(estimator = model,param_distributions=params,cv=5,scoring='accuracy')

In [31]:
randomcv.fit(X_train,y_train)

/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1194, in fit
    solver =

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [32]:
randomcv.best_score_

np.float64(0.8700000000000001)

In [33]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 0.01}

In [34]:
y_pred = randomcv.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score = accuracy_score(y_test,y_pred)
print("score: ",score)
cm = confusion_matrix(y_test,y_pred)
print("confusion matrix: ",cm)
print(classification_report(y_test,y_pred))

score:  0.8433333333333334
confusion matrix:  [[132  26]
 [ 21 121]]
              precision    recall  f1-score   support

           0       0.86      0.84      0.85       158
           1       0.82      0.85      0.84       142

    accuracy                           0.84       300
   macro avg       0.84      0.84      0.84       300
weighted avg       0.84      0.84      0.84       300



# Logistic Regression for multi-class classification

In [38]:
from sklearn.datasets import make_classification
# when classes > 2 use n_informative paramter as well before that
X,y=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=15)



In [39]:
X

array([[-1.28613186, -0.64833414,  1.04411477, ..., -1.3164116 ,
         1.01191003, -0.89806282],
       [-0.22222406,  2.083232  ,  1.19111402, ...,  0.98140271,
        -1.62879759,  1.37759419],
       [-0.43196264,  0.37574543, -1.37033375, ...,  1.2926021 ,
         0.925545  ,  0.23270542],
       ...,
       [-0.16384636, -0.41072503,  0.73908587, ...,  0.55830515,
         1.08971786, -0.26627295],
       [ 1.74969059, -1.12416838,  0.19980683, ...,  0.75255654,
         0.32229436, -0.17334302],
       [-0.24755583, -1.1705942 , -1.14058569, ...,  0.2063625 ,
         1.84351802, -0.81483138]])

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [41]:
# give multi class paramter as ovr for multi class classification
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr')

In [43]:
logistic.fit(X_train,y_train)


/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [44]:
y_pred = logistic.predict(X_test)

In [45]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score = accuracy_score(y_test,y_pred)
print("score: ",score)
cm = confusion_matrix(y_test,y_pred)
print("confusion matrix: ",cm)
print(classification_report(y_test,y_pred))

score:  0.79
confusion matrix:  [[84 10  8]
 [ 3 74 25]
 [10  7 79]]
              precision    recall  f1-score   support

           0       0.87      0.82      0.84       102
           1       0.81      0.73      0.77       102
           2       0.71      0.82      0.76        96

    accuracy                           0.79       300
   macro avg       0.79      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300



In [ ]:
# do hyperparameter tuing to improve accuracy
# 3x3 matrix so diagnol eleemnts are true prediction and rest are false


In [46]:
model = LogisticRegression(multi_class='ovr')
randomcv = RandomizedSearchCV(estimator = model,param_distributions=params,cv=5,scoring='accuracy')

In [47]:
randomcv.fit(X_train,y_train)


/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/user/Desktop/a/venv/lib/python3.10/site-packages/sklearn/linear

RandomizedSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
                   param_distributions={'C': [100, 10, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [48]:
y_pred = randomcv.predict(X_test)

In [49]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score = accuracy_score(y_test,y_pred)
print("score: ",score)
cm = confusion_matrix(y_test,y_pred)
print("confusion matrix: ",cm)
print(classification_report(y_test,y_pred))

score:  0.79
confusion matrix:  [[84 10  8]
 [ 3 74 25]
 [10  7 79]]
              precision    recall  f1-score   support

           0       0.87      0.82      0.84       102
           1       0.81      0.73      0.77       102
           2       0.71      0.82      0.76        96

    accuracy                           0.79       300
   macro avg       0.79      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300



In [50]:
randomcv.best_estimator_

LogisticRegression(C=100, multi_class='ovr', solver='newton-cg')

In [51]:
randomcv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 100}